### PR TITLE
Include module resources in `planned_values_resources`

### LINKED ISSUE #23: Add support for terraform modules
We make extensive use of terraform modules, but it appears that only the top-level resources in a project are included in `configuration_resources` and `planned_values_resources`.

I experimented with trying to change `lib/fugue_regula.rego` but I wasn't able to get very far.

The Terraform JSON output has `planned_values` map with `resources` inside the `root_module` key. But `root_module` also has a `child_modules` key, with a list of maps, and those have `resource` keys as well.

### PR DESCRIPTION
**Pull request by valdisrigdon**
Fixes #23

### CODE REVIEW

**Comment by valdisrigdon** [comment]
This is a start to add support for module output. I was able to successfully incorporate it for planned resources, but I don't think it's possible for the configuration values based on my reading of the JSON internals of terraform.

Feel free to leave comments and I can try to update -- I have very little experience with `rego` and this is first attempt at trying something like this.

**Comment by jaspervdj-luminal** [comment]
Hey @valdisrigdon, this is super helpful!

I think some pieces are still missing since `child_modules` can themselves have further `child_modules`, resulting in a recursive structure.  This means that we'll probably need to use Rego's `walk()` built-in function to search the whole JSON tree for further modules -- it sounds a bit complex, but maybe there's an easier way, too.

I have some time today to dig into this; and your example & code definitely put me on the right track, so thanks again!

**Comment by valdisrigdon** [comment]
@jaspervdj-luminal That's great! Any insight into the configuration_values section? Based on the JSON internals documentation and some examples, the `address` isn't a fully qualified path so I'm not sure how to incorporation that here.

**Comment by jaspervdj-luminal** [comment]
Right, thanks for pointing me to that.  There seems to be two more problems:

1. The addresses within `configuration_values` will need to go through some renaming phase to fully qualify them on the regula side.
2. Child modules can use a combination of input variables & output values to pass addresses in between them.  We need to make sure all these combinations work.

Both of these will probably require some non-trivial string parsing and construction bits.  I've put up some code [here](https://github.com/fugue/regula/pull/25) but it will require some more thought, so I don't expect to finish this today.

**Comment by valdisrigdon** [comment]
Closing in favor of #25

**Pull request closed without merging**
