### PR TITLE
Add compact output mode.

### PR DESCRIPTION
**Pull request by evan-fugue**
I haven't tested *extensively*, but here is a first stab at a compact output mode:

Screen Shot 2021-09-09 at 3 07 23 PM

### CODE REVIEW

**Comment by evan-fugue** [comment]
Here is an even more compact version which makes the rule ID a link so there is no need to include the URL.  I kept the cyan color for now, but changing it to blue (or anything else) would be trivial.

```diff
diff --git a/pkg/reporter/compact.tmpl b/pkg/reporter/compact.tmpl
index 7d9e6d6..4aa721e 100644
--- a/pkg/reporter/compact.tmpl
+++ b/pkg/reporter/compact.tmpl
@@ -3,13 +3,14 @@
 {{- /* RULE HEADER */ -}}
 {{- if $ruleResults.Results }}
 {{- if $ruleResults.RuleID }}
+{{- if not (eq $ruleResults.RuleRemediationDoc "") -}}
+{{- Cyan (LinkedText $ruleResults.RuleRemediationDoc $ruleResults.RuleID) }}
+{{- else -}}
 {{- Cyan $ruleResults.RuleID }}
+{{- end -}}
 {{- else -}}
 {{- Cyan $ruleResults.RuleName }}
-{{- end -}}: {{- Bold " " $ruleResults.RuleSummary }} {{ Severity $ruleResults.RuleSeverity }}
-{{- if not (eq $ruleResults.RuleRemediationDoc "") }}
-     {{ PadIndex nil (len $ruleResults.RuleID) }} {{ Link $ruleResults.RuleRemediationDoc }}
-{{- end -}}
+{{- end -}}: {{- Bold " " $ruleResults.RuleSummary }} {{ Severity $ruleResults.RuleSeverity -}}
 {{/* RULE RESULTS FOR A SINGLE RULE */}}
 {{- range $index, $rr := $ruleResults.Results }}
   {{ ResultIndex $rr $index }} {{ $rr.ResourceID }}
diff --git a/pkg/reporter/text.go b/pkg/reporter/text.go
index fea5c68..bf4d8cb 100644
--- a/pkg/reporter/text.go
+++ b/pkg/reporter/text.go
@@ -73,6 +73,9 @@ func CreateTextReporterTemplate(tmpl string) *template.Template {
                        "Link": func(items ...interface{}) string {
                                return color.New(color.FgHiBlue).Sprint(items...)
                        },
+                       "LinkedText": func(url string, text string) string {
+                               return fmt.Sprintf("\x1b]8;;%s\x1b\\%s\x1b]8;;\x1b\\", url, text)
+                       },
                        "Praise": func() string {
                                return randomPraise()
                        },
```

Patch goes on top of the patch in this PR.  I'm not sure if this is a good idea or not; terminal support for links is limited, but since compact isn't the default output maybe it would be okay.

**Comment by evan-fugue** [comment]
I just pushed some tweaks to make it even more compact.  Same deal, it's just another optional patch which can easily be dropped or squashed.  Here is a screenshot:

Screen Shot 2021-09-10 at 11 09 20 AM

I don't think there is really anything else to strip out.

**Review by curtis-fugue — APPROVED** [review]
I like it a lot 👍

**Review by jason-fugue — APPROVED** [review]
This is great!

**Pull request merged**
