### PR TITLE
add option to use existing json

### PR DESCRIPTION
**Pull request by ismailyenigul**
add parameter --terraform-dir,  --terraform-json and --rego-paths to be able to consume existing json plan file instead of creating from scratch

### CODE REVIEW

**Comment by jaspervdj-luminal** [comment]
Hey @ismailyenigul, thanks for the PR!  Running regula against an existing JSON file is something other people have asked about as well, so this is more than welcome!

I'm a bit concerned about backwards-compatibility though: if someone currently has:

```bash
regula terraform-dir rego-path-1 rego-path-2
```

in their CI configuration then that would break and they'd need to update to the new format.

It's only slightly inconvenient, but I think we can avoid it by allowing both forms:

```bash
regula terraform-dir rego-path-1 rego-path-2
regula plan.json rego-path-1 rego-path-2
```

We can simply use `test -f` or `test -d` in `bash` to figure out if we're dealing with a directory or a file and then call the corresponding code.  Does that make sense?

**Comment by ismailyenigul** [comment]
I see. then we should check the first parameter whether it has `.json` extension or not right?
or what do you prefer?

**Comment by jaspervdj-luminal** [comment]
I think checking if it's a file or directory is better than checking if it's `.json` since I've also seen the `.tfplan` extension being used.  So I would do something like:

```bash
if [[ -d "$2" ]]; then
    TERRAFORM_DIR="$1"
elif [[ -f "$2" ]]; then
    TERRAFORM_PLAN_JSON="$2"
else
    echo "Error: $2 should be a file or directory"
    exit 1
fi
```

**Comment by ismailyenigul** [comment]
That is fine and easiest way :). Do you want to update the PR  or should I do it?

**Comment by jaspervdj-luminal** [comment]
Feel free to do it if you have the time, it's awesome to get contributions! :-)

**Comment by ismailyenigul** [comment]
ok sorted!

**Review by jaspervdj-luminal — APPROVED** [review]

**Comment by jaspervdj-luminal** [comment]
Thanks a lot!

**Pull request merged**
