### PR TITLE
[RM-5612] Regula configuration file

### PR DESCRIPTION
**Pull request by jason-fugue**
This PR adds a configuration file feature to regula. The configuration file is created through `regula init` command and currently only applies to the `regula run` command.

Because it's only possible to use one configuration file at a time, I've also made it so that `--input-type` can be specified multiple times. I also refactored some of the `cmd` code around flags in order to cut down on repeated descriptions and parsing code.

### CODE REVIEW

**Review by becki-at-luminal — APPROVED** [review]
Docs look amazing! 🚀

**Review by curtis-fugue — APPROVED** [review]
This is great.

Having log output for "Using config file" is nice, at the same time it looks a bit weird since that's the only log output (with a log level prefix). I could see dropping the log level prefix, but I'm not sure about this.

A future enhancement could be to warn the user if they run `regula run` with options that are in the configuration file, since the configuration file options take precedence it looks like.

**Comment by jason-fugue** [comment]
> Having log output for "Using config file" is nice, at the same time it looks a bit weird since that's the only log output (with a log level prefix). I could see dropping the log level prefix, but I'm not sure about this.

I think we want to keep the log level for `WARNING` and `FATAL` messages, so I could just print that message to stderr instead of using logrus.

> A future enhancement could be to warn the user if they run `regula run` with options that are in the configuration file, since the configuration file options take precedence it looks like.

The command line options should take precedence with `regula run`, so I should fix that if they aren't. Do you have an example of when that happens?

**Review by jaspervdj-luminal — APPROVED** [review]
Awesome!

**Pull request merged**
